const Lang = {
  en: {
    search: "Search",
    gptSearchplaceholder: "What would you like to watch today?",
    Now_Playing: "Now Playing",
    Popular: "Popular",
    Top_Rated: "Top Rated",
    Upcoming: "Upcoming",
    Sign_Out:"Sign Out",
    Home_Page:"Home Page",
    GPT_Search:"GPT Search",
    APIrequestPlaceHolder:"Please enter valid OpenAI API key",
    use:"Use",
    AboutAPIrequest:"Notice: Kindly use the OpenAI API key to search the movies using the gpt-3.5-turbo model. The key will be stored in local storage.",
  },
  tamil: {
    search: "தேடு",
    gptSearchplaceholder: "இன்று நீங்கள் என்ன பார்க்க விரும்புகிறீர்கள்?",
    Now_Playing: "இப்போது திரையரங்கில் படங்கள்",
    Popular: "புகழ்பெற்ற படங்கள்",
    Top_Rated: "சிறந்த மதிப்பிடப்பட்ட படங்கள்",
    Upcoming: "வரவிருக்கும்",
    Sign_Out:"லாக் அவுட்",
    Home_Page:"முகப்பு பக்கம்",
    GPT_Search:"GPT தேடு",
    APIrequestPlaceHolder:"சரியான OpenAI API விசையை உள்ளிடவும்",
    use:"பயன்படுத்து",
    AboutAPIrequest:"அறிவிப்பு: gpt-3.5-turbo மாதிரியைப் பயன்படுத்தி திரைப்படங்களைத் தேட, OpenAI API விசையைப் பயன்படுத்தவும். விசை local storage சேமிக்கப்படும்.",
  },
  spanish: {
    search: "Buscar",
    gptSearchplaceholder: "¿Qué te gustaría ver hoy?",
    Now_Playing: "Películas en cines ahora",
    Popular: "Peliculas famosas",
    Top_Rated: "Películas mejor valoradas",
    Upcoming: "próximas películas",
    Sign_Out:"CerrarSesión",
    Home_Page:"PáginaDeInicio",
    GPT_Search:"GptBuscar",
    APIrequestPlaceHolder:"Ingrese una clave API de OpenAI válida",
    use:"Usar",
    AboutAPIrequest:"Aviso: utilice la clave API de OpenAI para buscar películas utilizando el modelo gpt-3.5-turbo. La clave se almacenará en el almacenamiento local.",
  },
};

export default Lang;
